/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RP = 3;
  /** RegularExpression Id. */
  int LP = 4;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int MUL = 6;
  /** RegularExpression Id. */
  int LB = 7;
  /** RegularExpression Id. */
  int RB = 8;
  /** RegularExpression Id. */
  int SC = 9;
  /** RegularExpression Id. */
  int SPACE = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int MAIN = 12;
  /** RegularExpression Id. */
  int FUNC = 13;
  /** RegularExpression Id. */
  int PARAM = 14;
  /** RegularExpression Id. */
  int NUM = 15;
  /** RegularExpression Id. */
  int EOL = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\")\"",
    "\"(\"",
    "\"+\"",
    "\"*\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\" \"",
    "\"DEF\"",
    "\"MAIN\"",
    "<FUNC>",
    "<PARAM>",
    "<NUM>",
    "\"\\n\"",
  };

}
